function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // obj_backgroundmusic
	global.__objectDepths[1] = 0; // obj_backgroundmoving
	global.__objectDepths[2] = 0; // obj_camera
	global.__objectDepths[3] = -1; // obj_player
	global.__objectDepths[4] = -1; // obj_player2
	global.__objectDepths[5] = 0; // obj_longjumpeffect
	global.__objectDepths[6] = 0; // obj_fireloss
	global.__objectDepths[7] = 0; // obj_squirteffect
	global.__objectDepths[8] = 0; // obj_squirtupeffect
	global.__objectDepths[9] = 0; // obj_cloudeffect
	global.__objectDepths[10] = 0; // obj_deadeffect
	global.__objectDepths[11] = -2; // obj_explosioneffect
	global.__objectDepths[12] = 0; // obj_dasheffect
	global.__objectDepths[13] = -2; // obj_destroyable1effect
	global.__objectDepths[14] = -1; // obj_splateffect
	global.__objectDepths[15] = -1; // obj_mayosplash
	global.__objectDepths[16] = -1; // obj_splooteffect
	global.__objectDepths[17] = -2; // obj_hurteffect
	global.__objectDepths[18] = -2; // obj_dashcloudeffect_panic
	global.__objectDepths[19] = -2; // obj_dashcloudeffect2
	global.__objectDepths[20] = -2; // obj_dashcloudeffect
	global.__objectDepths[21] = 0; // obj_pepgeteffect
	global.__objectDepths[22] = 0; // obj_fire1
	global.__objectDepths[23] = 0; // obj_fire2
	global.__objectDepths[24] = -2; // obj_handdrop2
	global.__objectDepths[25] = -2; // obj_handdrop
	global.__objectDepths[26] = 0; // obj_debris1
	global.__objectDepths[27] = 0; // obj_debris2
	global.__objectDepths[28] = 0; // obj_redfryboots
	global.__objectDepths[29] = 0; // obj_shopkeeper
	global.__objectDepths[30] = 0; // obj_bun
	global.__objectDepths[31] = 0; // obj_bun2
	global.__objectDepths[32] = 0; // obj_bunup
	global.__objectDepths[33] = 0; // obj_moto
	global.__objectDepths[34] = 1; // obj_carcrash
	global.__objectDepths[35] = 0; // signdown
	global.__objectDepths[36] = 0; // signup
	global.__objectDepths[37] = 6; // sign5
	global.__objectDepths[38] = 6; // sign1
	global.__objectDepths[39] = 6; // sign3
	global.__objectDepths[40] = 6; // sign2
	global.__objectDepths[41] = 6; // sign4
	global.__objectDepths[42] = 0; // obj_tipjar
	global.__objectDepths[43] = 0; // obj_stopcar
	global.__objectDepths[44] = 0; // obj_car
	global.__objectDepths[45] = 0; // obj_mop
	global.__objectDepths[46] = 1; // obj_coffee
	global.__objectDepths[47] = 0; // obj_burgballoon
	global.__objectDepths[48] = 0; // obj_hotsaucedispenser
	global.__objectDepths[49] = 0; // obj_crumblingfloor
	global.__objectDepths[50] = 0; // obj_checkpoint2
	global.__objectDepths[51] = 0; // obj_checkpoint1
	global.__objectDepths[52] = 0; // obj_lava
	global.__objectDepths[53] = 0; // obj_launchpad
	global.__objectDepths[54] = 4; // obj_carblock
	global.__objectDepths[55] = 4; // obj_blockwall
	global.__objectDepths[56] = 5; // obj_superdashblock
	global.__objectDepths[57] = 4; // obj_footblock
	global.__objectDepths[58] = 4; // obj_saltblock
	global.__objectDepths[59] = 4; // obj_corndogblock
	global.__objectDepths[60] = 0; // obj_spring
	global.__objectDepths[61] = 5; // obj_ladder
	global.__objectDepths[62] = 0; // obj_warp1
	global.__objectDepths[63] = 0; // obj_warp2
	global.__objectDepths[64] = 0; // obj_door2
	global.__objectDepths[65] = 0; // obj_door
	global.__objectDepths[66] = 4; // obj_movingwall
	global.__objectDepths[67] = 0; // obj_destroyable1
	global.__objectDepths[68] = 0; // obj_coin
	global.__objectDepths[69] = -3; // obj_pepper
	global.__objectDepths[70] = -3; // obj_hotsauce
	global.__objectDepths[71] = 0; // obj_finger
	global.__objectDepths[72] = -3; // obj_flyingpep
	global.__objectDepths[73] = 0; // obj_saltshaker
	global.__objectDepths[74] = -2; // obj_hotsauceprojectile
	global.__objectDepths[75] = 0; // obj_corndog
	global.__objectDepths[76] = 0; // obj_bomb1
	global.__objectDepths[77] = 6; // obj_target
	global.__objectDepths[78] = 0; // obj_button
	global.__objectDepths[79] = 5; // obj_wall
	global.__objectDepths[80] = 0; // obj_water
	global.__objectDepths[81] = -1; // obj_bombflame
	global.__objectDepths[82] = -1; // obj_bombexplosion
	global.__objectDepths[83] = 0; // obj_bossbomb
	global.__objectDepths[84] = 0; // obj_fryboysboss
	global.__objectDepths[85] = 0; // obj_tutorialboss
	global.__objectDepths[86] = 0; // obj_baddie
	global.__objectDepths[87] = 0; // obj_hurtthingie
	global.__objectDepths[88] = 6; // obj_shoottarget
	global.__objectDepths[89] = 0; // obj_hand
	global.__objectDepths[90] = 0; // obj_hand2
	global.__objectDepths[91] = 0; // obj_deadenemy
	global.__objectDepths[92] = 0; // obj_burgthrow
	global.__objectDepths[93] = 0; // obj_baddie_burglar
	global.__objectDepths[94] = 0; // obj_clownburg
	global.__objectDepths[95] = 0; // obj_burgjump
	global.__objectDepths[96] = 0; // obj_disc
	global.__objectDepths[97] = 0; // obj_hairfry
	global.__objectDepths[98] = 0; // obj_hairfryprojectile
	global.__objectDepths[99] = 0; // obj_frymoto
	global.__objectDepths[100] = 0; // obj_redfry
	global.__objectDepths[101] = 0; // obj_baddie_fry
	global.__objectDepths[102] = 0; // obj_fistfry_hitbox
	global.__objectDepths[103] = 0; // obj_fistfry
	global.__objectDepths[104] = 0; // obj_attackShitbox
	global.__objectDepths[105] = 0; // obj_attackhitbox
	global.__objectDepths[106] = 0; // obj_attackhitbox2
	global.__objectDepths[107] = 0; // obj_dashattackhitbox
	global.__objectDepths[108] = 0; // obj_dashattackhitbox2
	global.__objectDepths[109] = 0; // obj_attackdownhitbox
	global.__objectDepths[110] = 0; // obj_attackdownhitbox2
	global.__objectDepths[111] = 0; // obj_attackuphitbox
	global.__objectDepths[112] = 0; // obj_attackuphitbox2
	global.__objectDepths[113] = -2; // obj_ketchupbullet
	global.__objectDepths[114] = -2; // obj_mustardbullet
	global.__objectDepths[115] = 0; // obj_saltshotgunbullet
	global.__objectDepths[116] = 0; // obj_mayobullet
	global.__objectDepths[117] = 0; // obj_throwprojectile
	global.__objectDepths[118] = 0; // obj_saltbullet
	global.__objectDepths[119] = -2; // obj_fistbullet
	global.__objectDepths[120] = -2; // obj_superketchupbullet
	global.__objectDepths[121] = -2; // obj_supermustardbullet
	global.__objectDepths[122] = 0; // obj_transition
	global.__objectDepths[123] = 0; // obj_transitionboss
	global.__objectDepths[124] = 0; // obj_transition2
	global.__objectDepths[125] = 0; // obj_winner
	global.__objectDepths[126] = 0; // obj_tutorial
	global.__objectDepths[127] = 0; // obj_handS2
	global.__objectDepths[128] = 0; // obj_handS
	global.__objectDepths[129] = 0; // obj_select
	global.__objectDepths[130] = 0; // obj_your
	global.__objectDepths[131] = 0; // obj_food
	global.__objectDepths[132] = 0; // obj_exclamation
	global.__objectDepths[133] = 0; // obj_charselectcursor1
	global.__objectDepths[134] = 0; // obj_charselectcursor2
	global.__objectDepths[135] = 0; // obj_burgselect
	global.__objectDepths[136] = 0; // obj_wienerselect
	global.__objectDepths[137] = 0; // obj_null
	global.__objectDepths[138] = 0; // obj_controller_wave
	global.__objectDepths[139] = 0; // obj_player_wave


	global.__objectNames[0] = "obj_backgroundmusic";
	global.__objectNames[1] = "obj_backgroundmoving";
	global.__objectNames[2] = "obj_camera";
	global.__objectNames[3] = "obj_player";
	global.__objectNames[4] = "obj_player2";
	global.__objectNames[5] = "obj_longjumpeffect";
	global.__objectNames[6] = "obj_fireloss";
	global.__objectNames[7] = "obj_squirteffect";
	global.__objectNames[8] = "obj_squirtupeffect";
	global.__objectNames[9] = "obj_cloudeffect";
	global.__objectNames[10] = "obj_deadeffect";
	global.__objectNames[11] = "obj_explosioneffect";
	global.__objectNames[12] = "obj_dasheffect";
	global.__objectNames[13] = "obj_destroyable1effect";
	global.__objectNames[14] = "obj_splateffect";
	global.__objectNames[15] = "obj_mayosplash";
	global.__objectNames[16] = "obj_splooteffect";
	global.__objectNames[17] = "obj_hurteffect";
	global.__objectNames[18] = "obj_dashcloudeffect_panic";
	global.__objectNames[19] = "obj_dashcloudeffect2";
	global.__objectNames[20] = "obj_dashcloudeffect";
	global.__objectNames[21] = "obj_pepgeteffect";
	global.__objectNames[22] = "obj_fire1";
	global.__objectNames[23] = "obj_fire2";
	global.__objectNames[24] = "obj_handdrop2";
	global.__objectNames[25] = "obj_handdrop";
	global.__objectNames[26] = "obj_debris1";
	global.__objectNames[27] = "obj_debris2";
	global.__objectNames[28] = "obj_redfryboots";
	global.__objectNames[29] = "obj_shopkeeper";
	global.__objectNames[30] = "obj_bun";
	global.__objectNames[31] = "obj_bun2";
	global.__objectNames[32] = "obj_bunup";
	global.__objectNames[33] = "obj_moto";
	global.__objectNames[34] = "obj_carcrash";
	global.__objectNames[35] = "signdown";
	global.__objectNames[36] = "signup";
	global.__objectNames[37] = "sign5";
	global.__objectNames[38] = "sign1";
	global.__objectNames[39] = "sign3";
	global.__objectNames[40] = "sign2";
	global.__objectNames[41] = "sign4";
	global.__objectNames[42] = "obj_tipjar";
	global.__objectNames[43] = "obj_stopcar";
	global.__objectNames[44] = "obj_car";
	global.__objectNames[45] = "obj_mop";
	global.__objectNames[46] = "obj_coffee";
	global.__objectNames[47] = "obj_burgballoon";
	global.__objectNames[48] = "obj_hotsaucedispenser";
	global.__objectNames[49] = "obj_crumblingfloor";
	global.__objectNames[50] = "obj_checkpoint2";
	global.__objectNames[51] = "obj_checkpoint1";
	global.__objectNames[52] = "obj_lava";
	global.__objectNames[53] = "obj_launchpad";
	global.__objectNames[54] = "obj_carblock";
	global.__objectNames[55] = "obj_blockwall";
	global.__objectNames[56] = "obj_superdashblock";
	global.__objectNames[57] = "obj_footblock";
	global.__objectNames[58] = "obj_saltblock";
	global.__objectNames[59] = "obj_corndogblock";
	global.__objectNames[60] = "obj_spring";
	global.__objectNames[61] = "obj_ladder";
	global.__objectNames[62] = "obj_warp1";
	global.__objectNames[63] = "obj_warp2";
	global.__objectNames[64] = "obj_door2";
	global.__objectNames[65] = "obj_door";
	global.__objectNames[66] = "obj_movingwall";
	global.__objectNames[67] = "obj_destroyable1";
	global.__objectNames[68] = "obj_coin";
	global.__objectNames[69] = "obj_pepper";
	global.__objectNames[70] = "obj_hotsauce";
	global.__objectNames[71] = "obj_finger";
	global.__objectNames[72] = "obj_flyingpep";
	global.__objectNames[73] = "obj_saltshaker";
	global.__objectNames[74] = "obj_hotsauceprojectile";
	global.__objectNames[75] = "obj_corndog";
	global.__objectNames[76] = "obj_bomb1";
	global.__objectNames[77] = "obj_target";
	global.__objectNames[78] = "obj_button";
	global.__objectNames[79] = "obj_wall";
	global.__objectNames[80] = "obj_water";
	global.__objectNames[81] = "obj_bombflame";
	global.__objectNames[82] = "obj_bombexplosion";
	global.__objectNames[83] = "obj_bossbomb";
	global.__objectNames[84] = "obj_fryboysboss";
	global.__objectNames[85] = "obj_tutorialboss";
	global.__objectNames[86] = "obj_baddie";
	global.__objectNames[87] = "obj_hurtthingie";
	global.__objectNames[88] = "obj_shoottarget";
	global.__objectNames[89] = "obj_hand";
	global.__objectNames[90] = "obj_hand2";
	global.__objectNames[91] = "obj_deadenemy";
	global.__objectNames[92] = "obj_burgthrow";
	global.__objectNames[93] = "obj_baddie_burglar";
	global.__objectNames[94] = "obj_clownburg";
	global.__objectNames[95] = "obj_burgjump";
	global.__objectNames[96] = "obj_disc";
	global.__objectNames[97] = "obj_hairfry";
	global.__objectNames[98] = "obj_hairfryprojectile";
	global.__objectNames[99] = "obj_frymoto";
	global.__objectNames[100] = "obj_redfry";
	global.__objectNames[101] = "obj_baddie_fry";
	global.__objectNames[102] = "obj_fistfry_hitbox";
	global.__objectNames[103] = "obj_fistfry";
	global.__objectNames[104] = "obj_attackShitbox";
	global.__objectNames[105] = "obj_attackhitbox";
	global.__objectNames[106] = "obj_attackhitbox2";
	global.__objectNames[107] = "obj_dashattackhitbox";
	global.__objectNames[108] = "obj_dashattackhitbox2";
	global.__objectNames[109] = "obj_attackdownhitbox";
	global.__objectNames[110] = "obj_attackdownhitbox2";
	global.__objectNames[111] = "obj_attackuphitbox";
	global.__objectNames[112] = "obj_attackuphitbox2";
	global.__objectNames[113] = "obj_ketchupbullet";
	global.__objectNames[114] = "obj_mustardbullet";
	global.__objectNames[115] = "obj_saltshotgunbullet";
	global.__objectNames[116] = "obj_mayobullet";
	global.__objectNames[117] = "obj_throwprojectile";
	global.__objectNames[118] = "obj_saltbullet";
	global.__objectNames[119] = "obj_fistbullet";
	global.__objectNames[120] = "obj_superketchupbullet";
	global.__objectNames[121] = "obj_supermustardbullet";
	global.__objectNames[122] = "obj_transition";
	global.__objectNames[123] = "obj_transitionboss";
	global.__objectNames[124] = "obj_transition2";
	global.__objectNames[125] = "obj_winner";
	global.__objectNames[126] = "obj_tutorial";
	global.__objectNames[127] = "obj_handS2";
	global.__objectNames[128] = "obj_handS";
	global.__objectNames[129] = "obj_select";
	global.__objectNames[130] = "obj_your";
	global.__objectNames[131] = "obj_food";
	global.__objectNames[132] = "obj_exclamation";
	global.__objectNames[133] = "obj_charselectcursor1";
	global.__objectNames[134] = "obj_charselectcursor2";
	global.__objectNames[135] = "obj_burgselect";
	global.__objectNames[136] = "obj_wienerselect";
	global.__objectNames[137] = "obj_null";
	global.__objectNames[138] = "obj_controller_wave";
	global.__objectNames[139] = "obj_player_wave";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
